---
#Provision some instances:
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
  - group_vars/all
 
  tasks:
  - name: Launch webserver instances
    ec2: >
     aws_access_key=AKIAJ2QFRL6ZIL5YAOFQ
     aws_secret_key=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
     keypair="{{ ec2_keypair }}"
     group="{{ ec2_security_group }}"
     type="{{ ec2_instance_type }}"
     image="{{ ec2_image }}"
     region="{{ ec2_region }}"
     count="{{ ec2_instance_count }}"
     wait=true
    register: ec2

#  - name: Wait for SSH to come up
#    local_action: wait_for host={{ item.public_dns_name }}
#      port=22 delay=60 timeout=320 state=started
#    with_items: ec2.instances

  - debug: var=ec2.instances.public_dns_name

